---
- name: Скачать и распаковать архив
  hosts: all
  become: yes
  vars:
    download_url: "https://www.apache.org/dyn/closer.lua/kafka/4.3.1/kafka-4.3.1-src.tgz?action=download"
    extract_dir: "/opt/kafka"
    archive_dest: "/tmp/kafka.tgz"

  tasks:
    - name: Создать каталог для распаковки
      ansible.builtin.file:
        path: "{{ extract_dir }}"
        state: directory
        mode: '0755'

    - name: Скачать архив
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "{{ archive_dest }}"
        mode: '0644'

    - name: Установить tar
      ansible.builtin.package:
        name: tar
        state: present

    - name: Распаковать архив
      ansible.builtin.unarchive:
        src: "{{ archive_dest }}"
        dest: "{{ extract_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
